name: Auto Delete Merged Branch

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  delete:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete head branch after merge
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const branch = pr.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            try {
              await github.rest.git.deleteRef({ owner, repo, ref: `heads/${branch}` });
              core.info(`Deleted branch ${branch}`);
            } catch (e) {
              core.info('Could not delete branch: ' + (e.message || e));
            }

