name: PR Template Coach

on:
  workflow_run:
    workflows: ["PR Template Check"]
    types: [completed]

jobs:
  coach:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment guidance on PR
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const prs = run.pull_requests || [];
            if (!prs.length) {
              core.info('No PR attached to this workflow run.');
              return;
            }
            const prNumber = prs[0].number;
            const body = `🚦 PR Template Check failed. Please update the PR body using the required sections.\n\nRequired sections:\n- Summary\n- Linked Issues (use \`Closes #<id>\`)\n- Affected Areas\n- Test & Checks\n\nHelpers:\n- \`make pr-template\` → generates PR_BODY.md\n- Edit PR_BODY.md\n- \`make pr-update PR=${prNumber}\` → updates PR and re-runs the check\n\nSee scripts/pr-body-sample.md for a scaffold.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body,
            });
