name: PR Template Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body has required sections
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.pull_request && context.payload.pull_request.body) || "";
            const required = ["Summary", "Linked Issues", "Affected Areas", "Test & Checks"]; // Minimal required sections
            const missing = required.filter(h => !body.toLowerCase().includes(h.toLowerCase()));
            if (!body.trim()) {
              core.setFailed("PR body is empty. Please use the pull request template.");
            } else if (missing.length) {
              core.setFailed(`PR body missing required sections: ${missing.join(", ")}. Please fill out the template.`);
            } else {
              core.info("PR template sections present");
            }
